# Generated by Django 5.2.1 on 2025-05-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maszyny', '0002_maszyna_liczba_maszyn_alter_maszyna_kategoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maszyna',
            options={'ordering': ['-created_at'], 'verbose_name': 'Maszyna', 'verbose_name_plural': 'Maszyny'},
        ),
        migrations.RenameField(
            model_name='maszyna',
            old_name='data_dodania',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='maszyna',
            name='link_youtube',
            field=models.URLField(blank=True, help_text='Link do filmu na YouTube', null=True),
        ),
        migrations.AddField(
            model_name='maszyna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
